### ISSUE TITLE
Practica_Frontend

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-trabajo-is#2]
[PRACTICA_FRONTEND.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-trabajo-is/files/6549051/PRACTICA_FRONTEND.pdf)

**Comment by EDITH-R** [comment]
Calificación 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
